server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.anyframe.cloud: DEBUG

spring:
  output:
    ansi:
      enabled: true
#  dao:
#    exceptiontranslation:
#      enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:anyframe;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: anyframecloud
    password:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
